
import { 
  LayoutDashboard, 
  ClipboardList, 
  Package, 
  Cpu, 
  FileBarChart, 
  Settings, 
  Bell, 
  Search, 
  Plus, 
  MoreVertical, 
  Filter,
  AlertTriangle,
  Calendar,
  CheckCircle,
  XCircle,
  Clock,
  ChevronDown,
  ChevronUp,
  Download,
  User,
  Wrench,
  Users,
  Lock,
  LogOut,
  Trash2,
  Edit2,
  FileText,
  Truck,
  Receipt,
  ShoppingBag,
  FileSpreadsheet,
  UploadCloud,
  PackageMinus,
  History,
  Hammer,
  HardHat,
  ClipboardCheck,
  AlertOctagon,
  TimerReset,
  Gauge,
  ArrowRight,
  ChevronsRight,
  ChevronsLeft,
  TrendingUp,
  Sun,
  Moon
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Orders: ClipboardList,
  Inventory: Package,
  Components: Cpu,
  Cpu: Cpu,
  Reports: FileBarChart,
  FileBarChart: FileBarChart,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  Plus: Plus,
  More: MoreVertical,
  Filter: Filter,
  Alert: AlertTriangle,
  Calendar: Calendar,
  Check: CheckCircle,
  CheckCircle: CheckCircle,
  X: XCircle,
  Clock: Clock,
  Down: ChevronDown,
  Up: ChevronUp,
  Download: Download,
  User: User,
  Tool: Wrench,
  Users: Users,
  Lock: Lock,
  Logout: LogOut,
  Trash: Trash2,
  Edit: Edit2,
  FileText: FileText,
  Truck: Truck,
  Receipt: Receipt,
  ShoppingBag: ShoppingBag,
  Excel: FileSpreadsheet,
  Upload: UploadCloud,
  Consumption: PackageMinus,
  History: History,
  Panol: Hammer,
  Helmet: HardHat,
  Checklist: ClipboardCheck,
  Danger: AlertOctagon,
  LifeCycle: TimerReset,
  Meter: Gauge,
  ArrowRight: ArrowRight,
  ChevronsRight: ChevronsRight,
  ChevronsLeft: ChevronsLeft,
  TrendingUp: TrendingUp,
  Sun: Sun,
  Moon: Moon
};
